const {home, professor, members:memberGroups, projects, publications, courses, memories}=window.LAB_DATA;
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
const heading=(name,desc='')=>`<div class="page"><div class="section-label">UNIST Safe AI Lab</div><h1 class="page-heading" tabindex="-1">${name}</h1>${desc?`<p class="lead">${desc}</p>`:''}`;

// Official publication pages and author repositories. Add further links here,
// or add paperUrl / githubUrl to an entry in content.js (those take precedence).
const publicationResources = {
  "MIG-COW: Transferable Adversarial Attacks on Deepfake Detectors via Gradient Decomposition": {
    "paperUrl": "https://dl.acm.org/doi/abs/10.1145/3746027.3761986"
  },
  "Fair Sampling in Diffusion Models through Switching Mechanism": {
    "paperUrl": "https://ojs.aaai.org/index.php/AAAI/article/view/30202"
  },
  "Proactive Defense Benchmark against Deepfake Generation": {
    "paperUrl": "https://icml.cc/virtual/2026/poster/62016",
    "githubUrl": "https://github.com/proactivedefensebenchmark/proactivedefensebenchmark"
  },
  "Privacy-Preserving Embedding via Look-up Table Evaluation with Homomorphic Encryption": {
    "paperUrl": "https://proceedings.mlr.press/v235/kim24ab.html"
  },
  "Fairness Audit of Machine Learning Models with Confidential Computing": {
    "paperUrl": "https://doi.org/10.1145/3485447.3512244"
  },
  "Lipschitz-Certifiable Training with a Tight Outer Bound": {
    "paperUrl": "https://proceedings.neurips.cc/paper_files/paper/2020/hash/c46482dd5d39742f0bfd417b492d0e8e-Abstract.html",
    "githubUrl": "https://github.com/sungyoon-lee/bcp"
  },
  "Seq2Synth: Benchmarking Temporal Fidelity in Synthetic Sequential Tabular Data": {
    "paperUrl": "https://arxiv.org/abs/2607.15606"
  },
  "Unlearning's Blind Spots: Over-Unlearning and Prototypical Relearning Attack": {
    "paperUrl": "https://arxiv.org/abs/2506.01318"
  },
  "Multi-modal guided super-resolution thermal imaging for coal pile monitoring": {
    "paperUrl": "https://doi.org/10.1016/j.jestch.2026.102312"
  },
  "MER-SoLa: Confusion-based soft labeling for Multimodal Emotion Recognition": {
    "paperUrl": "https://doi.org/10.1145/3746270.3760220"
  },
  "Verifiable computation over encrypted data via MPC-in-the-head zero-knowledge proofs": {
    "paperUrl": "https://doi.org/10.1007/s10207-024-00941-w"
  },
  "Privacy-preserving Inference Resistant to Model Extraction Attacks": {
    "paperUrl": "https://doi.org/10.1016/j.eswa.2024.124830"
  },
  "Efficient Privacy-Preserving Counting Method with Homomorphic Encryption": {
    "paperUrl": "https://doi.org/10.1007/978-981-96-5566-3_7"
  },
  "The SaTML'24 CNN Interpretability Competition: New Innovations for Concept-Level Interpretability": {
    "paperUrl": "https://arxiv.org/abs/2404.02949"
  },
  "Efficient Differentially Private Kernel Support Vector Classifier for Multi-class Classification": {
    "paperUrl": "https://doi.org/10.1016/j.ins.2022.10.075"
  },
  "Privacy-preserving Fair Learning of Support Vector Machine with Homomorphic Encryption": {
    "paperUrl": "https://doi.org/10.1145/3485447.3512252"
  },
  "Efficient homomorphic encryption framework for privacy-preserving regression": {
    "paperUrl": "https://doi.org/10.1007/s10489-022-04015-z"
  },
  "Efficient Generation of Program Execution Hash": {
    "paperUrl": "https://doi.org/10.1109/ACCESS.2022.3181283"
  },
  "Stability Analysis of Denoising Autoencoder based on Dynamical Projection System": {
    "paperUrl": "https://doi.org/10.1109/TKDE.2020.3010277"
  },
  "Privacy-Preserving Evaluation for Support Vector Clustering": {
    "paperUrl": "https://doi.org/10.1049/ell2.12047"
  },
  "HE-Friendly Algorithm for Privacy-Preserving SVM Training": {
    "paperUrl": "https://doi.org/10.1109/ACCESS.2020.2981818"
  },
  "Semi-supervised Distributed Representation of documents for Sentiment Analysis": {
    "paperUrl": "https://doi.org/10.1016/j.neunet.2019.08.001"
  },
  "Privacy- Preserving Support Vector Machine with Fully-Homomorphic Encryption": {
    "paperUrl": "https://ceur-ws.org/Vol-2301/paper_35.pdf"
  },
  "Loss-driven Ensemble Deep Learning for Online Time Series Analysis": {
    "paperUrl": "https://www.mdpi.com/2071-1050/11/12/3489"
  },
  "Learning of indiscriminate distributions of document embeddings for domain adaptation": {
    "paperUrl": "https://doi.org/10.3233/IDA-184131"
  },
  "Learning Representative Exemplars Using Gaussian Process Regression": {
    "paperUrl": "https://doi.org/10.1016/j.patcog.2017.09.002"
  },
  "Defensive denoising methods against adversarial attack": {
    "paperUrl": "https://www.kdd.org/kdd2018/files/deep-learning-day/DLDay18_paper_33.pdf"
  },
  "Information-based Boundary Equilibrium Generative Adversarial Networks with Interpretable Representation Learning": {
    "paperUrl": "https://doi.org/10.1155/2018/6465949"
  },
  "Instance Weighting Domain Adaptation Using Distance Kernel": {
    "paperUrl": "https://doi.org/10.7232/iems.2018.17.2.334"
  },
  "Inductive ensemble clustering using kernel support matching": {
    "paperUrl": "https://doi.org/10.1049/el.2017.2159"
  },
  "Predicting Market Impact Costs Using Nonparametric Machine Learning Models": {
    "paperUrl": "https://doi.org/10.1371/journal.pone.0150243"
  },
  "Secure Training Support Vector Machine with Partial Sensitive Part": {
    "paperUrl": "https://doi.org/10.9708/jksci.2021.26.04.001"
  },
  "An Efficient Deep Learning Ensemble Using a Distribution of Label Embedding": {
    "paperUrl": "https://doi.org/10.9708/jksci.2021.26.01.027"
  }
};
function resourceURL(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}}
function publicationLinks(p){const saved=publicationResources[p.title]||{};const links=[['Paper',p.paperUrl??saved.paperUrl],['GitHub',p.githubUrl??saved.githubUrl]].map(([label,url])=>{const href=resourceURL(url);return href?`<a class="pub-resource" href="${e(href)}" target="_blank" rel="noopener noreferrer" aria-label="${label}: ${e(p.title)} (opens in a new tab)">${label} <span aria-hidden="true">↗</span></a>`:''}).join('');return links?`<div class="pub-resources">${links}</div>`:''}
const publicationLinkStyles=`<style>.author-dagger{font-size:.7em;line-height:0;vertical-align:super;margin-left:.04em}.pub-resources{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 4px}.pub-resource{display:inline-flex;align-items:center;gap:10px;padding:6px 12px;border:1px solid #b9cdcf;border-radius:6px;color:#076b75;background:#f1f7f7;font-size:13px;font-weight:600;text-decoration:none}.pub-resource:hover{background:#dceeee}.pub-resource:focus-visible,.research-paper-title:focus-visible{outline:2px solid #087f8c;outline-offset:4px}.research-paper-title{font:inherit;color:inherit;text-align:left;background:none;border:0;padding:0;cursor:pointer;line-height:1.6}.research-paper-title:hover{text-decoration:underline;color:var(--topic)}.research-paper-title span{white-space:nowrap}</style>`;
let pendingPublicationTitle='';
document.addEventListener('click',event=>{const button=event.target.closest('[data-publication-title]');if(!button)return;pendingPublicationTitle=button.dataset.publicationTitle;if(location.hash==='#publications')route();else location.hash='publications'});

// Research page content. Edit descriptions and related publication titles below.
const researchTopics = [
  {id:'privacy',color:'#087f8c',label:'01 / PRIVACY',title:'Privacy-Preserving ML',tagline:'Learn from data. Protect what is sensitive.',intro:'How can we use sensitive data without unnecessarily exposing the people and organizations behind it? We study learning and inference methods that integrate privacy and security into the computational process.',detail:'Our interests include homomorphic encryption, secure computation, and differential privacy. We examine how these approaches interact with model design, computational efficiency, and the information revealed by model outputs. Privacy is considered across the workflow, from training and representation learning to inference and statistical analysis.',methods:['Homomorphic encryption','Secure computation','Differential privacy','Federated Learning','Unlearning'],pipeline:['Sensitive data','Protected computation','Useful output'],caption:'A conceptual workflow for learning with protected data.',papers:["Privacy-Preserving Embedding via Look-up Table Evaluation with Homomorphic Encryption","Efficient Privacy-Preserving Counting Method with Homomorphic Encryption","Privacy-preserving Inference Resistant to Model Extraction Attacks","Verifiable computation over encrypted data via MPC-in-the-head zero-knowledge proofs","Efficient Differentially Private Kernel Support Vector Classifier for Multi-class Classification","Efficient homomorphic encryption framework for privacy-preserving regression","Privacy-preserving Fair Learning of Support Vector Machine with Homomorphic Encryption"]},
  {id:'fairness',color:'#6953ab',label:'02 / FAIRNESS',title:'Fairness-Aware ML',tagline:'Examine who benefits—and who is left behind.',intro:'An accurate model can still behave differently across populations. We study how to examine these differences and how fairness requirements can be evaluated alongside privacy and security constraints.',detail:'Our work connects fairness-aware learning with verification and certification. Rather than relying only on a single aggregate score, we consider the choice of fairness criteria, the data used for evaluation, and the assumptions behind an assessment. A central question is how to audit models while protecting confidential information.',methods:['Fairness verification','Confidential auditing','Fair learning'],pipeline:['Groups & criteria','Audit model behavior','Evaluate disparities'],caption:'Fairness assessment depends on the groups, criteria, and context.',papers:["Fairness Audit of Machine Learning Models with Confidential Computing","Privacy-preserving Fair Learning of Support Vector Machine with Homomorphic Encryption","Fair Sampling in Diffusion Models through Switching Mechanism","Effects of Generative Model Collapse on Demographic Fairness in Healthcare Data","Bias and Fairness in Diffusion Autoencoders: Identity Removal through Latent Attacks"]},
  {id:'security',color:'#b85c34',label:'03 / SECURITY',title:'Security-Enhanced ML',tagline:'Understand attacks. Build stronger defenses.',intro:'Machine learning systems can be attacked through their inputs, training data, and interfaces. We investigate these vulnerabilities to better understand when models fail and how defenses should be evaluated.',detail:'Research interests include adversarial attacks, poisoning and backdoor attacks, model extraction, and the security of generative models. We consider the attacker’s capabilities and objectives, how attacks transfer between settings, and whether a defense remains effective under meaningful changes to the threat model.',methods:['Adversarial robustness','Backdoor attacks','Model extraction','Generative-model security'],pipeline:['Threat model','Attack & defense','Robustness evaluation'],caption:'Security evaluation begins with an explicit threat model.',papers:["LogoGate: Object-Aware Logo-Exposure Backdoor Attack for Text-to-Image Models","BaSTion: Backdoor Style Trigger Restoration Method via GANs and Style Transfer Networks","Unlearning's Blind Spots: Over-Unlearning and Prototypical Relearning Attack","Proactive Defense Benchmark against Deepfake Generation","MIG-COW: Transferable Adversarial Attacks on Deepfake Detectors via Gradient Decomposition","Privacy-preserving Inference Resistant to Model Extraction Attacks","Lipschitz-Certifiable Training with a Tight Outer Bound","Defensive denoising methods against adversarial attack"]},
  {id:'learning',color:'#26764d',label:'04 / LEARNING',title:'Statistical Learning',tagline:'Understand representations across changing data.',intro:'Models often encounter data that differs from the data used to develop them. We study representations and learning methods that help us reason about these changes and make better use of information across domains.',detail:'Our interests include deep representation learning, transfer learning, and statistical analysis. We explore how the structure of a learned representation relates to the task and data distribution, and how information from one domain can support learning in another. These questions connect statistical foundations with the broader goal of reliable AI.',methods:['Representation learning','Transfer learning','Domain adaptation'],pipeline:['Source domain','Learn representations','Target domain'],caption:'Transfer learning connects representations across domains.',papers:["Seq2Synth: Benchmarking Temporal Fidelity in Synthetic Sequential Tabular Data","MER-SoLa: Confusion-based soft labeling for Multimodal Emotion Recognition","Stability Analysis of Denoising Autoencoder based on Dynamical Projection System","Learning of indiscriminate distributions of document embeddings for domain adaptation","Learning Representative Exemplars Using Gaussian Process Regression","Instance Weighting Domain Adaptation Using Distance Kernel","The SaTML'24 CNN Interpretability Competition: New Innovations for Concept-Level Interpretability"]}
];
// Add topics: ['privacy', 'security'] to publications in content.js.
// Explicit topics override the legacy title mapping; [] hides a paper from Related work.
// Newest year first; publications listed earlier win ties within the same year.
function relatedPublications(topic) {
  return publications
    .filter(p => Array.isArray(p.topics) ? p.topics.includes(topic.id) : topic.papers.includes(p.title))
    .sort((a, b) => (Number(b.year) || 0) - (Number(a.year) || 0))
    .slice(0, 3);
}
function researchFigure(t){return `<svg viewBox="0 0 320 128" aria-hidden="true" focusable="false"><g fill="none" stroke="currentColor" stroke-width="1.5"><rect x="15" y="32" width="72" height="65" rx="12" opacity=".4"/><rect x="124" y="20" width="72" height="89" rx="12"/><rect x="233" y="32" width="72" height="65" rx="12" opacity=".4"/><path d="M88 64h34m75 0h34"/><path d="m116 59 6 5-6 5m109-10 6 5-6 5"/></g>${t.id==='privacy'?'<g fill="currentColor"><circle cx="39" cy="54" r="4"/><circle cx="62" cy="54" r="4"/><circle cx="39" cy="75" r="4"/><circle cx="62" cy="75" r="4"/></g><g fill="none" stroke="currentColor" stroke-width="2"><rect x="144" y="57" width="32" height="25" rx="4"/><path d="M149 57V47a11 11 0 0 1 22 0v10m-11 12v7M249 65l12 10 26-28"/></g>':t.id==='fairness'?'<g stroke="currentColor" stroke-width="5" stroke-linecap="round"><path d="M36 53h30M36 76h30M144 54h32M144 76h32M253 54h32M253 76h32"/></g>':t.id==='security'?'<g fill="none" stroke="currentColor" stroke-width="2"><path d="m37 49 27 30m0-30L37 79M160 38l22 8v21q0 16-22 26-22-10-22-26V46Z M149 65l8 8 15-19 M249 65l12 10 26-28"/></g>':'<g fill="currentColor"><circle cx="35" cy="52" r="4"/><circle cx="52" cy="80" r="4"/><circle cx="68" cy="62" r="4"/><circle cx="148" cy="48" r="5"/><circle cx="174" cy="61" r="5"/><circle cx="148" cy="83" r="5"/><circle cx="252" cy="55" r="4"/><circle cx="275" cy="72" r="4"/><circle cx="283" cy="47" r="4"/></g><path d="m148 48 26 13-26 22Z" fill="none" stroke="currentColor"/>'}</svg>`}
const researchStyles=`<style>
.research-overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:40px 0 72px}.topic-card{color:var(--topic);border:1px solid #dce3e4;background:white;text-align:left;border-radius:16px;padding:22px 20px;transition:transform .2s,box-shadow .2s;font:inherit;display:flex;flex-direction:column;min-width:0}.topic-card:hover,.topic-card:focus-visible{transform:translateY(-5px);box-shadow:0 12px 26px #16323812;border-color:var(--topic)}.topic-card[aria-current="true"]{border-color:var(--topic);box-shadow:inset 0 3px var(--topic)}.topic-label{font-size:12px;letter-spacing:1.7px;font-weight:700}.topic-card svg{width:100%;height:auto;margin:25px 0 18px}.topic-card h2{color:var(--ink);font-size:23px;line-height:1.2;font-weight:500;letter-spacing:-.6px;margin:0 0 14px}.topic-card p{color:var(--muted);font-size:14px;line-height:1.5;margin:0 0 24px}.topic-action{font-size:14px;margin-top:auto}.research-detail{scroll-margin-top:32px;border-top:1px solid var(--line);padding:48px 0 64px;display:grid;grid-template-columns:1fr 1.65fr;gap:7%}.research-detail h2{font-size:clamp(30px,3.7vw,46px);line-height:1.1;font-weight:500;letter-spacing:-1.6px;margin:20px 0}.research-tagline{font-size:19px;color:var(--muted);line-height:1.5}.research-body>p{line-height:1.85;margin:0 0 22px;color:var(--muted)}.research-body>p:first-child{font-size:20px;color:var(--ink);line-height:1.65}.research-body h3{font-size:18px;margin:28px 0 16px}.research-methods{display:flex;flex-wrap:wrap;gap:8px;margin-top:25px}.research-methods span{padding:6px 11px;border:1px solid var(--line);border-radius:5px;font-size:13px;color:var(--topic)}.research-flow{margin:30px 0;padding:24px;border-radius:12px;background:#eef3f4}.research-flow-steps{display:flex;align-items:center;gap:10px}.research-flow-steps span{flex:1;text-align:center;background:white;border:1px solid #d7e1e3;border-radius:6px;padding:13px 8px;font-size:13px;line-height:1.4}.research-flow-steps b{color:var(--topic);font-weight:400}.research-flow figcaption{font-size:12px;color:var(--muted);margin-top:14px}.research-paper{font-size:15px;line-height:1.6;padding:14px 0;border-bottom:1px solid var(--line);margin:0;color:var(--muted)}.research-back{border:0;background:none;color:var(--topic);font-size:14px;padding:10px 0;margin-top:20px}.research-detail:focus{outline:none}.research-detail:focus-visible{outline:2px solid var(--topic);outline-offset:8px}@media(max-width:1000px){.research-overview{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.research-detail{grid-template-columns:1fr;gap:20px;padding:36px 0}.research-overview{gap:12px;margin-bottom:44px}.topic-card{padding:17px 14px}.topic-card h2{font-size:19px}.topic-card p{font-size:14px}.topic-card svg{margin:16px 0}.research-flow{padding:16px}.research-flow-steps{gap:5px}.research-flow-steps span{font-size:12px;padding:12px 5px}}@media(prefers-reduced-motion:reduce){.topic-card{transition:none}.topic-card:hover{transform:none}}
</style>`;
function renderResearch(){return heading('Research','Exploring the foundations of secure, fair, and reliable machine learning.')+researchStyles+publicationLinkStyles+`<div class="research-overview" role="navigation" id="research-topics" aria-label="Explore research topics">${researchTopics.map(t=>`<button type="button" class="topic-card" style="--topic:${t.color}" data-research-target="research-${t.id}" aria-controls="research-${t.id}"><span class="topic-label">${t.label}</span>${researchFigure(t)}<h2>${e(t.title)}</h2><p>${e(t.tagline)}</p><span class="topic-action">Explore topic ↓</span></button>`).join('')}</div>${researchTopics.map(t=>`<section class="research-detail" id="research-${t.id}" tabindex="-1" style="--topic:${t.color}"><div><span class="topic-label" style="color:var(--topic)">${t.label}</span><h2>${e(t.title)}</h2><p class="research-tagline">${e(t.tagline)}</p><div class="research-methods">${t.methods.map(m=>`<span>${e(m)}</span>`).join('')}</div></div><div class="research-body"><p>${e(t.intro)}</p><p>${e(t.detail)}</p><figure class="research-flow"><div class="research-flow-steps">${t.pipeline.map((s,i)=>`${i?'<b aria-hidden="true">→</b>':''}<span>${e(s)}</span>`).join('')}</div><figcaption>${e(t.caption)}</figcaption></figure><h3>Related work</h3>${relatedPublications(t).map(p=>`<div class="research-paper"><button type="button" class="research-paper-title" data-publication-title="${e(p.title)}">${e(p.title)} <span aria-hidden="true">↗</span></button>${publicationLinks(p)}</div>`).join('')}<a class="text-link" href="#publications" style="margin-top:20px">View publications ↗</a><br><button type="button" class="research-back" data-research-target="research-topics">Back to topics ↑</button></div></section>`).join('')}</div>`}
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-research-target]');if(!trigger)return;const target=document.getElementById(trigger.dataset.researchTarget);if(!target)return;document.querySelectorAll('.topic-card').forEach(card=>card.setAttribute('aria-current',String(card.dataset.researchTarget===target.id)));target.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});if(target.matches('section'))target.focus({preventScroll:true});else target.querySelector('button')?.focus({preventScroll:true})});

const pages={
home:()=>`<section class="hero">${home.bannerImage?`<img class="hero-image" src="${e(home.bannerImage)}" alt="${e(home.bannerAlt)}" style="object-position:${e(home.bannerPosition||'center center')}">`:''}<div class="hero-meta">${e(home.affiliation)}</div><div class="hero-content"><div class="eyebrow">${e(home.eyebrow)}</div><h1>${e(home.titleFirstLine)}<span>${e(home.titleSecondLine)}</span></h1><p>${e(home.subtitle).replaceAll('\n','<br>')}</p></div></section><section class="home-intro"><div class="section-label">${e(home.introLabel)}</div><div><h2>${e(home.introTitle).replaceAll('\n','<br>')}</h2><p>${e(home.introText)}</p><a class="text-link" href="#research">${e(home.researchLinkText)}</a></div></section>`,
professor:()=>heading('Professor')+`<section class="profile"><div><img class="professor-photo" src="${e(professor.photo)}" alt="${e(professor.name)}"><p class="section-label">Assistant Professor</p><a class="text-link" href="${e(professor.website)}" target="_blank" rel="noopener">Personal website ↗</a></div><div><span class="section-label">${e(professor.role)}</span><h2>${e(professor.name)}</h2><div class="bio">${professor.bio.map(p=>`<p>${e(p)}</p>`).join('')}</div><dl><dt>Affiliation</dt><dd>Department of Industrial Engineering, UNIST</dd><dt>Email</dt><dd><a href="mailto:${e(professor.email)}">${e(professor.email)}</a></dd><dt>Phone</dt><dd>+82 52 217 7599</dd></dl><section class="profile-section"><h3>Research</h3><p>Secure and stable machine learning, including stability analysis, adversarially robust training, and privacy-preserving learning through encryption. Other interests include unsupervised transfer learning and secure analytics for fair machine learning.</p><div class="research-tags"><span class="badge">Privacy-Preserving ML</span><span class="badge">Adversarial Robustness</span><span class="badge">Fair Machine Learning</span></div></section><section class="profile-section"><h3>Education & Experience</h3><h4>Education</h4><p><strong>Ph.D., Industrial Engineering</strong><br>Seoul National University · February 2018</p><p>Thesis: Density-based Representation Learning with Applications to Sentiment Analysis and Domain Adaptation</p><p><strong>B.S., Industrial Engineering</strong><br>Seoul National University · February 2013</p><h4>Experience</h4><p><strong>Assistant Professor · UNIST</strong><br>Department of Industrial Engineering · March 2023 – Present</p><p><strong>Assistant Professor · Sungshin Women’s University</strong><br>Department of Convergence Security Engineering · September 2019 – February 2023</p><p><strong>Researcher · Seoul National University</strong><br>Industrial and Mathematical Data Analytics Research Center · March 2018 – August 2019</p><p><strong>Visiting Scholar · UCLA</strong><br>Institute for Pure and Applied Mathematics · September – December 2018</p></section></div></section></div>`,
members:()=>heading('Members','The people behind our research.')+memberGroups.map(group=>`<section class="member-section"><h2>${e(group.title)}</h2><div class="member-grid">${group.people.map(m=>`<article class="member">${m.photo?`<img class="member-portrait" src="${e(m.photo)}" alt="${e(m.name)}" loading="lazy">`:`<div class="member-portrait" aria-label="Photo unavailable">${e(m.name.split(' ').map(s=>s[0]).join(''))}</div>`}<h3>${e(m.name)}</h3><p class="member-interest">${e(m.interest||'Research interests to be added')}</p><p class="member-detail"><span>Research period</span>${e(m.period)}</p><p class="member-detail"><span>Email</span>${m.email?`<a href="mailto:${e(m.email)}">${e(m.email)}</a>`:'Not listed'}</p></article>`).join('')}</div></section>`).join('')+'</div>',
research:()=>renderResearch(),
projects:()=>heading('Projects','Research initiatives in secure and trustworthy AI.')+`<fieldset class="project-filters"><legend>Project status</legend><label><input type="checkbox" id="project-all" checked> All</label><label><input type="checkbox" id="project-ongoing" checked> Ongoing</label><label><input type="checkbox" id="project-completed" checked> Completed</label></fieldset><p class="project-count" id="project-count" aria-live="polite"></p><div id="project-results"></div></div>`,
publications:()=>heading('Publications')+publicationLinkStyles+`<div class="filters"><label>Search publications<input id="search" type="search" placeholder="Search by author, title or keyword"></label><label>Filter<select id="type"><option value="">All</option><option>Conference</option><option>Journal</option><option>International</option><option>Domestic</option></select></label><label>Year<select id="pubyear"><option value="">All years</option>${[...new Set(publications.map(p=>p.year))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join('')}</select></label></div><div class="resultbar"><span aria-live="polite">Results <strong id="count"></strong></span><button class="reset" id="reset">Reset</button></div><div id="pubresults"></div></div>`,
courses:()=>heading('Courses','Teaching at UNIST.')+`<section>${[...courses].sort((a,b)=>{const rank=term=>{const [year,season]=term.trim().split(/\s+/);return Number(year)*10+({spring:1,summer:2,fall:3,autumn:3,winter:4}[season?.toLowerCase()]||0)};return rank(b.term)-rank(a.term)}).map(c=>`<article class="course"><span>${e(c.term)}</span><h3>${e(c.title)}</h3><div><span class="badge">${e(c.level)}</span></div></article>`).join('')}</section></div>`,
memories:()=>heading('Memories','Life, in and around the lab.')+memories.map((m,i)=>`<article class="memory"><div class="stack"><img id="memory-${i}" src="${e(m.photos[0])}" alt="${e(m.title)} — photo 1" loading="lazy" tabindex="0" aria-label="${e(m.title)}: use left and right arrow keys to browse"></div><div><span class="section-label">${e(m.date)}</span><h2>${e(m.title)}</h2><p>${e(m.description)}</p><div class="stack-controls"><button class="round" data-album="${i}" data-step="-1" aria-label="${e(m.title)}: previous photo">←</button><span class="counter" id="counter-${i}" aria-live="polite">01 / ${String(m.photos.length).padStart(2,'0')}</span><button class="round" data-album="${i}" data-step="1" aria-label="${e(m.title)}: next photo">→</button></div></div></article>`).join('')+'</div>'
};
function renderProjects(){const ongoing=document.querySelector('#project-ongoing').checked,completed=document.querySelector('#project-completed').checked,all=document.querySelector('#project-all');all.checked=ongoing&&completed;all.indeterminate=ongoing!==completed;const items=projects.filter(p=>p.status==='Ongoing'?ongoing:completed);document.querySelector('#project-count').textContent=`${items.length} project${items.length===1?'':'s'}`;document.querySelector('#project-results').innerHTML=items.length?items.map(p=>`<article class="project-row"><span class="badge ${p.status==='Completed'?'completed':''}">${e(p.status)}</span><div><h2>${e(p.title)}</h2>${p.description?`<p>${e(p.description)}</p>`:''}<p class="project-period">${e(p.period)}</p></div></article>`).join(''):'<p class="empty">Select Ongoing or Completed to view projects.</p>'}
function renderPubs(){const q=document.querySelector('#search').value.toLowerCase().trim(),t=document.querySelector('#type').value,y=document.querySelector('#pubyear').value;const result=publications.filter(p=>(!q||`${p.title} ${p.authors} ${p.venue}`.toLowerCase().includes(q))&&(!t||p.type===t||p.scope===t)&&(!y||p.year===Number(y)));document.querySelector('#count').textContent=result.length;document.querySelector('#pubresults').innerHTML=result.length?['International','Domestic'].map(scope=>{const list=result.filter(p=>p.scope===scope);return list.length?`<details class="pubgroup" open><summary>${scope} publications</summary>${list.map(p=>`<article class="publication"><div class="pubmeta"><span>${e(p.venue)}</span><span>${p.year}</span>${p.translated?'<span>English translation</span>':''}</div><h3>${e(p.title)}</h3><p>${e(p.authors).replaceAll('Saerom Park','<strong>Saerom Park</strong>').replaceAll('Jieun Yun','<strong>Jieun Yun</strong>').replaceAll('Joonhyuk Baek','<strong>Joonhyuk Baek</strong>').replaceAll('Kiwan Kwon','<strong>Kiwan Kwon</strong>').replaceAll('Hojin Lee','<strong>Hojin Lee</strong>').replaceAll('Jaeyun Kim','<strong>Jaeyun Kim</strong>').replaceAll('Yeseong Jung','<strong>Yeseong Jung</strong>').replaceAll('Wonjune Seo','<strong>Wonjune Seo</strong>').replaceAll('Sangah Park','<strong>Sangah Park</strong>').replaceAll('†','<sup class="author-dagger">†</sup>')}</p>${publicationLinks(p)}</article>`).join('')}</details>`:''}).join(''):'<p class="empty">No matching publications. Try another search or reset the filters.</p>'}
let albumIndices=memories.map(()=>0);
function stepAlbum(i,delta){const m=memories[i];albumIndices[i]=(albumIndices[i]+delta+m.photos.length)%m.photos.length;const n=albumIndices[i],img=document.querySelector(`#memory-${i}`);img.src=m.photos[n];img.alt=`${m.title} — photo ${n+1}`;document.querySelector(`#counter-${i}`).textContent=`${String(n+1).padStart(2,'0')} / ${String(m.photos.length).padStart(2,'0')}`}
function closeMenus(){document.querySelectorAll('.drop>button').forEach(b=>{b.setAttribute('aria-expanded','false');document.getElementById(b.getAttribute('aria-controls')).hidden=true})}
function route(){const id=location.hash.slice(1)||'home';document.querySelector('#main').innerHTML=(pages[id]||pages.home)();document.title=`${id==='home'?'':(id.charAt(0).toUpperCase()+id.slice(1)+' | ')}UNIST Safe AI Lab`;document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.hash===`#${id}`);if(a.hash===`#${id}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.querySelectorAll('.drop>button').forEach(b=>b.classList.toggle('active',[...b.nextElementSibling.querySelectorAll('a')].some(a=>a.hash===`#${id}`)));closeMenus();document.querySelector('nav').classList.remove('open');document.querySelector('.mobile-toggle').setAttribute('aria-expanded','false');
if(id==='projects'){renderProjects();document.querySelector('#project-all').onchange=event=>{document.querySelector('#project-ongoing').checked=event.target.checked;document.querySelector('#project-completed').checked=event.target.checked;renderProjects()};document.querySelector('#project-ongoing').onchange=renderProjects;document.querySelector('#project-completed').onchange=renderProjects}
if(id==='publications'){if(pendingPublicationTitle){document.querySelector('#search').value=pendingPublicationTitle;pendingPublicationTitle=''}renderPubs();document.querySelectorAll('.filters input,.filters select').forEach(el=>el.addEventListener('input',renderPubs));document.querySelector('#reset').onclick=()=>{document.querySelectorAll('.filters input,.filters select').forEach(el=>el.value='');renderPubs()}}
if(id==='memories'){albumIndices=memories.map(()=>0);document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>stepAlbum(+b.dataset.album,+b.dataset.step));memories.forEach((m,i)=>{const img=document.querySelector(`#memory-${i}`);img.onkeydown=event=>{if(['ArrowRight','ArrowLeft'].includes(event.key)){event.preventDefault();stepAlbum(i,event.key==='ArrowRight'?1:-1)}};let start;img.addEventListener('touchstart',event=>start=event.changedTouches[0].clientX,{passive:true});img.addEventListener('touchend',event=>{const d=event.changedTouches[0].clientX-start;if(Math.abs(d)>40)stepAlbum(i,d<0?1:-1)},{passive:true})})}
window.scrollTo(0,0)}
document.querySelectorAll('.drop>button').forEach(b=>b.onclick=()=>{const was=b.getAttribute('aria-expanded')==='true';closeMenus();b.setAttribute('aria-expanded',String(!was));b.nextElementSibling.hidden=was});document.addEventListener('click',event=>{if(!event.target.closest('.drop'))closeMenus()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){const open=document.querySelector('.drop>button[aria-expanded="true"]');closeMenus();open?.focus()}});document.querySelector('.mobile-toggle').onclick=event=>{const open=document.querySelector('nav').classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open))};document.querySelector('#year').textContent=new Date().getFullYear();window.addEventListener('hashchange',route);route();
